### ISSUE TITLE
roles - admin

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#109]
**Beschreibung**
As an admin I want to have all rights a wimi has, and additionally I want to be able to:
- see all existing vms
- manage user rights (#110)
- see and manage vm-requests (#111)
- edit vm-templates (#98, should already be done)

in order to manage the tool efficiently.
The only thing I do not want to be able to do is see and change the ssh-key of a user that is not myself.

**Akzeptanzkriterien**
- [x] role of admin exists
- [x] stories #110 and #111 should be fulfilled
- [ ] only admin can add and edit vm-templates
- [x] the vm-page shows all existing vms
- [x] ssh-keys of other users are not visible or editable

**Priorität**

**Aufwandsschätzung**

**Tasks**
- [x] add admin to role enum on users
- [x] all employee restricted pages are also visible for admins
- [x] no filter from vm index page for admin
- [x] do #110 and #111

**Comment by skydivin4ng3l** [comment]
kind of depends on #112

**Comment by BjoernDaase** [comment]
@isabel-amon Please also add the ability to manage VM templates as an action an admin exclusively can do while WiMis (employees) and Users are not allowed to.
This is related to #98 which is finished and will hopefully merged today or tomorrow.

**Comment by lassesteffen** [comment]
As @skydivin4ng3l said, this should only happen after #112 is done

**Comment by skydivin4ng3l** [comment]
Komplexität

**Comment by lassesteffen** [comment]
@isabel-amon, an employee can currently see all vms on the index page, is that the wanted behaviour?

**Comment by isabel-amon** [comment]
@lassesteffen no, everyone should just see the vms that he is assigned to on the dashboard, except the admin, who sees all vms.

**Comment by isabel-amon** [comment]
please don't forget about the vm-template editing.

**Comment by lassesteffen** [comment]
Open Tasks
- [ ] hide edit vm templates for everyone but admins
- [ ] also filter vm for employees on vms/
