### ISSUE TITLE
restrict access to see and manage vm requests

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#111]
**Beschreibung**
As an admin I want to be the **only one** who can accept or reject a request for a new vm, so that not everyone can create and delete at will.

I want to be able to see all requests of all users.

This means, that **only I** want to click on "pending" next to a new request, which takes me to the page of the request where I can see the accept and reject buttons (not sure what the page is right now, please ask Björn). **Only I** should be able to see this page. When I accept a request I am taken to vms/new, this already works. **Only I** can see this page.

**Akzeptanzkriterien**
- [ ] Only admins see all requested vms
- [ ] Only admins are able to click on the "pending" next to a request 
- [ ] the page vms/requests is only visible to admins 
- [ ] The page vms/new is only visible to admins

**Priorität**

**Aufwandsschätzung**

**Tasks**
- [ ] add to/modify a ?detail request page? with accept and reject buttons
- [ ] add a pending button to requests on the request ?index? page
- [ ] limit access to admins

**Comment by skydivin4ng3l** [comment]
added some tasks.

what about the actual functionality of accepting a VM request, meaning do we have to initiate the actual creation of the VM or is this the @hpi-swt2/bd-18 job?

what about changing user access to the vm is this also to be managed by the admin, like wimi adds users x and this is a new request?

**Comment by BjoernDaase** [comment]
@skydivin4ng3l That's our job. It will be done in #152 next sprint.

**Comment by isabel-amon** [comment]
you can still see the list of requests when you are not an admin...

**Comment by janwestphal306** [comment]
@isabel-amon do you meen that the page `vms/requests` should be not accessable for other roles than admin or that the list of requests should be empty?
If the page should be accessable then this collides with the issue #113. In additon we are currently blocked at issue #113 because the creator of a request does not exist yet.

**Comment by isabel-amon** [comment]
No, it should not be accessible.
