### ISSUE TITLE
roles - wimi

### ISSUE THREAD

**Issue by isabel-amon** [hpi-swt2/vm-portal#112]
**Beschreibung**
As a wimi I want to be able to do everything a normal user can do, plus:
- request vms (#113 )

**Akzeptanzkriterien**
- [x] Role of wimi exists
- [ ] story #113

**Priorität**

**Aufwandsschätzung**

**Tasks**
- [x] add wimi to role enum
- [ ] whitelist vm request page
- [ ] do #113

**Comment by skydivin4ng3l** [comment]
kind of depends on #115

**Comment by skydivin4ng3l** [comment]
haben wir hier für eine komplexität?
