### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#16]
**Beschreibung**
**Als** Nutzer 
**möchte ich** ein Dashboard haben
**damit ich** eine Übersicht über alle relevanten Informationenauf einen Blick erhalte.

**Akzeptanzkriterien**
- [x] Nach dem Login gelange ich auf das Dashboard, es liegt auf "/"
- [x] Das Dashboard zeigt mir eine Liste mit allen Servern und VMs an, für die ich zuständig bin
- [x] In der Liste der Server/VMs sehe ich die wichtigsten Metriken des Servers bzw. der VM (zB Online/Offline-Status)

**Schätzung**
8

**Comment by mewitte** [comment]
# Tasks

- [ ] Dashboard erstellen 30min
- [ ] routes anpassen, login check auf root page 30min
- [ ] liste erstellen, layout entwerfen 2h
- [ ] vm Liste kopieren 30min
- [ ] vm Liste anpassen 30min
