### ISSUE TITLE
Edit VM information

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#237]
[//]: # (Lines starting with [//]: are considered to comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an employee or admin
I want to edit the information of a VM
in order to change eg. the user or project of a VM

**Acceptance Criteria:**

- [ ] A button on the VM detail page (/vms/:id) called "Edit" in the manage dropdown should link to a form (likely at /vms/:id/edit) that allows you to change the information of the VM.
- [ ] In the edit form, you can edit Users (Regular and Sudo) and Description.
- [ ] VM-Names explicitly cannot be edited.
- [ ] Clicking on a Save-button saves the edits and leads back to the detail page
- [ ] A notification is sent to any user who is granted or loses access rights through this.

Out-Off-Scope:
- Editing the Hardware specs of a VM after it was created is not part of this user story, but is still a goal later on.

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

Hint: please meet with persons responsible for the puppet scripts to make sure the changes will be synced to the puppet files. See #238

**Comment by hkohlsaat** [comment]
# Tasks
- [ ] Test existence of the "edit" button at /vms/:id (15 min)
- [ ] Test that the "edit" button links to the edit page (15 min)
- [ ] Add the "edit" button and create the edit page (also controller action) (30 min)
- [ ] Try to test the form (20 min)
- [ ] Create the form (30 min)
- [ ] Test for existence of the "save" button (15 min)
- [ ] Try to test saving behaviour (leading to the detail page again) (40 min)
- [ ] Add Save button (and create the corresponding controller action) (15 min)
- [ ] Test that the "person responsible for a VM cannot be removed from the access list" (15 min)
- [ ] Add a check for that in the model (25 min)
- [ ] Try testing notifications (30 min)
- [ ] Implement notifications for people with changed access rights (40 min)
