### ISSUE TITLE
Notification Seite

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#63]
**Beschreibung**
**Als** Nutzer
**möchte ich** Notifications die an mich gesendet wurden sehen können
**damit ich** diese lesen kann.

Eine Seite sollte mir meine Notifications untereinander in einer liste zeigen. Noch ungelesene Notifications sollten hervorgehoben sein, und es sollte einen Button geben um die notification als gelesen zu markieren (z.B. das Häkchen im Bild unten von github).
![image](https://user-images.githubusercontent.com/38384819/48903928-29798880-ee5d-11e8-9265-69e6cd5f6cd1.png)

**Akzeptanzkriterien**
 - [x] Es gibt eine Seite auf der ich meine Notifications sehen kann
 - [x] Ungelesene Notifications werden oben in der Liste angezeigt und hervorgehoben.
 - [x] Man kann einen notification per klick als gelesen markieren
 - [x] Notifications werden in chronologischer Reihenfolge mit den neusten zuerst angezeigt.

**Priorität**
Hoch

**Aufwandsschätzung**
10

**Comment by hkohlsaat** [comment]
# Tasks
- [ ] Tests schreiben - 30 min - @Adrian-St @hkohlsaat 
- [ ] scaffolden und anpassen - 30 min - @Adrian-St @hkohlsaat 
- [ ] Styling (hervorheben) - 30 min - @Adrian-St @hkohlsaat 
- [ ] Feature-Test für gelesen markieren - 30 min - @Adrian-St @hkohlsaat 
- [ ] javascript für gelesen markieren - 30 min - @Adrian-St @hkohlsaat
