### ISSUE TITLE
Darstellung von Notifications auf dem Dashboard

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#65]
**Beschreibung**
**Als** Nutzer
**möchte ich** in meinem Dashboard ungelesene notifications angezeigt bekommen
**damit ich** diese so schnell wie möglich sehe.

Auf dem Dashboard werden in einer Liste die neusten noch ungelesenen notifications direkt angezeigt, und können von dort aus direkt als gelesen markiert werden.
Es wird eine begrenzte anzahl an Notifications angezeigt (je nach größe der Listeneinträge 3-5 maximal), um die liste möglichst klein zu halten.

**Akzeptanzkriterien**
 - [ ] Es gibt auf dem Dashboard eine Liste, die die neuesten ungelesenen Notifications anzeigt
 - [ ] Man kann mit klick auf die Liste auf die Notification Page gelangen
 - [ ] Man kann Notifications direkt in der Liste als gelesen markieren

**Priorität**
Mittel

**Aufwandsschätzung**
3

**Comment by mewitte** [comment]
# Tasks
- [ ] Liste im Dashboard erstellen und Layout anpassen
- [ ] notifications in Liste einfügen
