### ISSUE TITLE
Darstellung von Notifications im Header

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#66]
**Beschreibung**
**Als** Nutzer
**möchte ich** im header ein icon haben, welches mir anzeigt, ob ich neue benachrichtigungen habe
**damit ich** sofort sehe, wenn ich neue benachrichtigungen habe.

Gewünscht ist eine glocke ähnlich dieser, mit einem roten icon das erscheint wenn ich neue Notifications habe. 
![image](https://user-images.githubusercontent.com/38384819/48904162-d522d880-ee5d-11e8-9891-d2a6626d26cf.png)

**Akzeptanzkriterien**
 - [ ] Ein Icon mit einer kleinen weißen Glocke ist im Header sichtbar
 - [ ] Wenn es ungelesene Notifications gibt ist ein roter kreis (vergleich oberes Bild) an der glocke zu sehen
 - [ ] Ein klick auf das icon bringt mich auf die Notifications page
 - [ ] Das Icon Updated ohne neu laden der Seite, mindestens alle 10 Minuten.

**Priorität**
Hoch

**Aufwandsschätzung**
8

**Comment by hkohlsaat** [comment]
# Tasks
- [ ] Icons heraussuchen - 30 min - @Adrian-St @hkohlsaat 
- [ ] Icons einbinden - 30 min - @Adrian-St @hkohlsaat 
- [ ] Header layout-Dateien refactorn - 30 min - @Adrian-St @hkohlsaat 
- [ ] Periodisches Update programmieren (javascript und Controller) - 1h - @Adrian-St @hkohlsaat
