### ISSUE TITLE
Favicon und Logo

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#68]
**Beschreibung**
**Als** Nutzer
**möchte ich** ein Favicon für die Seite in meinem Browser gezeigt bekommen
**damit ich** besser im browser mit der seite arbeiten kann.
Derzeitiger Zustand:
![image](https://user-images.githubusercontent.com/38384819/48904308-3a76c980-ee5e-11e8-9f86-82e6d80f50ca.png)
Im Browser sollte ein Favicon so dargestellt werden:
![image](https://user-images.githubusercontent.com/38384819/48904332-482c4f00-ee5e-11e8-93af-d0c1debb6362.png)

**Akzeptanzkriterien**
 - [ ] Es gibt ein Logo für die Seite
 - [ ] die Seite zeigt das Logo als Favicon im Browser an

**Priorität**
Mittel

**Aufwandsschätzung**
3

**Comment by phSch08** [comment]
# Tasks
- [ ] find/create Icon (1h) - @phSch08 
- [ ] set Icon as Favicon (15 min) - @phSch08 
- [ ] include Icon in Navbar (15 min) - @phSch08
