### ISSUE TITLE
Ein bisschen mehr Blau

### ISSUE THREAD

**Issue by arne-z** [hpi-swt2/vm-portal#94]
**Beschreibung**
**Als** Kunde
**möchte ich** ein bisschen mehr Blau
**damit ich** beim anblick der Seite nicht depressiv werde.

**Akzeptanzkriterien**
 - [ ] Die seite hat ein wenig mehr Farbe als Weiß und Grau

**Priorität**
Mittel

**Aufwandsschätzung**

**Comment by henleo** [comment]
**Tasks**
- [ ] Elemente finden die mehr Farbe vertragen könnten 1h
- [ ] evtl. Hintergrund für Startseite 1hmin
- [ ] Elementfraben ändern 30min
- [ ] evtl. neue Farben 30min
